import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Terms of Service',
  description:
    'MyToolOrbit terms of service. Terms governing the use of our free online tools platform.',
  alternates: { canonical: '/terms-of-service' },

  robots: { index: true, follow: true },
  openGraph: {
    title: 'Terms of Service',
    description: 'MyToolOrbit terms of service. Terms governing the use of our free online tools platform.',
    url: '/terms-of-service',
    type: 'website',
    siteName: 'MyToolOrbit',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Terms of Service',
    description: 'MyToolOrbit terms of service. Terms governing the use of our free online tools platform.',
  },
};

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl mb-8">
        Terms of Service
      </h1>
      <div className="space-y-6 text-secondary-muted leading-relaxed">
        <p className="text-sm text-secondary-muted/70">Last updated: September 2024</p>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Acceptance of terms</h2>
          <p>
            By accessing or using MyToolOrbit, you agree to be bound by these Terms of Service.
            If you do not agree with any part of these terms, you should not use the site.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Description of service</h2>
          <p>
            MyToolOrbit provides free online tools for developers, SEO professionals, and AI
            users. All tools are provided on an &quot;as is&quot; and &quot;as available&quot;
            basis without warranties of any kind.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Use of tools</h2>
          <p>
            You may use MyToolOrbit tools for personal and commercial purposes. You agree not
            to misuse the tools, attempt to reverse-engineer them, or use them in ways that
            violate applicable laws or regulations. The Broken Link Checker should be used
            responsibly — do not use it to overwhelm or attack third-party websites.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">No warranty</h2>
          <p>
            MyToolOrbit and its tools are provided without warranties of any kind, express or
            implied. We do not guarantee that the tools will be accurate, reliable, or available
            at all times. You use the tools at your own risk. The token counter provides
            approximate estimates only and should not be used for exact billing purposes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Limitation of liability</h2>
          <p>
            MyToolOrbit shall not be liable for any direct, indirect, incidental, or
            consequential damages arising from the use of or inability to use the tools. This
            includes, but is not limited to, data loss, business interruption, or any other
            damages resulting from the use of the platform.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Intellectual property</h2>
          <p>
            The MyToolOrbit brand, design, and original content are the property of MyToolOrbit.
            You may not copy, modify, or distribute our content without permission. The output
            generated by the tools (meta tags, schema markup, sitemaps, etc.) belongs to you
            and may be used freely.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Third-party links</h2>
          <p>
            MyToolOrbit may link to third-party websites. We are not responsible for the
            content, privacy policies, or practices of third-party sites.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Changes to terms</h2>
          <p>
            We may update these terms from time to time. We will update the &quot;last
            updated&quot; date at the top of this page. Continued use of MyToolOrbit after
            changes constitutes acceptance of the updated terms.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-foreground mb-3">Contact</h2>
          <p>
            If you have questions about these terms, please contact us at{' '}
            <a href="mailto:hello@mytoolorbit.com" className="text-primary hover:underline">
              hello@mytoolorbit.com
            </a>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
